### ISSUE TITLE
时间戳计算有误

### ISSUE THREAD

**Issue by gogogoghost** [chenhuaiyuan/alipay-rs#1]
作者您好，反馈一个BUG
版本：0.2.1
问题：凌晨12点时后，datetime()计算会返回24:xx:xx，导致支付宝网关返回非法时间戳
复现方法：将电脑时间调到凌晨0点后发送请求即可

我在如下位置打印了log：
![图片](https://user-images.githubusercontent.com/29392742/155889341-a2b678a4-6fa0-4149-a2c8-4c604a380972.png)
输出结果如下：
![图片](https://user-images.githubusercontent.com/29392742/155889392-68d1eafa-7a34-47e5-a0fd-f73e9ce5c21a.png)

本人rust学习尚浅，暂未能理解您为什么要移除chrono库自己实现一份时间格式化，所以也没有直接提PR，方便的话可以加以说明

感谢您分享了如此优秀的项目

**Comment by chenhuaiyuan** [comment]
非常感谢反馈，我已在第一时间修复这个bug，我来说说我为什么要移除chrono，因为chrono库是个非常强大、功能非常多的库，而我在这个项目中只使用到了一小小部分功能，完全没必要用到chrono库，又考虑到别人可能在自己的项目中未使用到chrono库来格式化时间，如果我在alipay-rs中使用的话只会增加程序的体积。

本人使用rust也没超过1年，也还在学习阶段，也说不上能力有多强，所以发现bug请及时PR吧。

**Comment by chenhuaiyuan** [comment]
> 作者您好，反馈一个BUG 版本：0.2.1 问题：凌晨12点时后，datetime()计算会返回24:xx:xx，导致支付宝网关返回非法时间戳 复现方法：将电脑时间调到凌晨0点后发送请求即可
> 
> 我在如下位置打印了log： ![图片](https://user-images.githubusercontent.com/29392742/155889341-a2b678a4-6fa0-4149-a2c8-4c604a380972.png) 输出结果如下： ![图片](https://user-images.githubusercontent.com/29392742/155889392-68d1eafa-7a34-47e5-a0fd-f73e9ce5c21a.png)
> 
> 本人rust学习尚浅，暂未能理解您为什么要移除chrono库自己实现一份时间格式化，所以也没有直接提PR，方便的话可以加以说明
> 
> 感谢您分享了如此优秀的项目

非常感谢反馈，我在第一时间修复了这个 bug，我说我为什么要移除 chrono，因为 chrono 库是个非常强大、非常多的库，而我在这个项目中只使用到了一小部分部分内容并没有及时在库中，考虑到其他项目未使用到库中的功能，还想及时，如果我的支付宝使用时增加程序的体积。

本人使用也没有生锈1年学习，也说不上水平以上能力，所以发现bug请及时公关吧。

**Comment by chenhuaiyuan** [comment]
@gogogoghost 
非常感谢反馈，我在第一时间修复了这个 bug，我说我为什么要移除 chrono，因为 chrono 库是个非常强大、非常多的库，而我在这个项目中只使用到了一小部分部分内容并没有及时在库中，考虑到其他项目未使用到库中的功能，还想及时，如果我的支付宝使用时增加程序的体积。

本人使用也没有生锈1年学习，也说不上水平以上能力，所以发现bug请及时公关吧。

**Comment by chenhuaiyuan** [comment]
@gogogoghost 
非常感谢反馈，我在第一时间修复了这个 bug，我来说说我为什么要移除 chrono，因为 chrono 库是个非常强大、非常多的库，而我在这个项目中只使用到了一小部分部分内容并没有及时在库中，考虑到其他项目未使用到库中的功能，还想及时，如果我的支付宝使用时增加程序的体积。

本人使用也没有生锈1年学习，也说不上水平以上能力，所以发现bug请及时公关吧。

**Comment by chenhuaiyuan** [comment]
@gogogoghost
非常感谢反馈，我已在第一时间修复了这个 bug，我来说说我为什么要移除 chrono，因为 chrono 库是个非常强大的库，而我在这个项目中只使用到了一小部分功能，为了这一小部分功能而去使用chrono库，我觉得完全没必要，又考虑到别人在其他项目中可能未使用到chrono库来格式化时间，如果我在alipay-rs这个项目中使用的话，只会增加程序的体积大小。

本人使用rust也没有超过1年，现在也还在努力学习rust，能力也说不上多强，所以发现bug请及时PR。
